/**
 * Friendbot funding with retry/backoff — testnet only.
 *
 * Friendbot is the only faucet used; it is called exclusively for the
 * throwaway public keys generated by `keys.ts`. An "account already funded"
 * response is treated as success so the flow is idempotent.
 */
import { TESTNET_HOSTS } from "./config.ts";

export interface FundResult {
  publicKey: string;
  alreadyFunded: boolean;
}

export interface FundOptions {
  friendbotUrl?: string;
  timeoutMs?: number;
  attempts?: number;
  baseDelayMs?: number;
  fetchImpl?: typeof fetch;
  sleep?: (ms: number) => Promise<void>;
}

const realSleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

export async function fundWithFriendbot(publicKey: string, opts: FundOptions = {}): Promise<FundResult> {
  const url = opts.friendbotUrl ?? TESTNET_HOSTS.friendbotUrl;
  if (url !== TESTNET_HOSTS.friendbotUrl) {
    throw new Error(`refusing to use a non-testnet friendbot: ${url}`);
  }
  const doFetch = opts.fetchImpl ?? fetch;
  const sleep = opts.sleep ?? realSleep;
  const attempts = opts.attempts ?? 4;
  const timeoutMs = opts.timeoutMs ?? 30_000;
  const baseDelayMs = opts.baseDelayMs ?? 1_000;

  let lastError: Error | undefined;
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    try {
      const res = await doFetch(`${url}?addr=${encodeURIComponent(publicKey)}`, {
        method: "GET",
        signal: AbortSignal.timeout(timeoutMs),
      });
      const text = await res.text();
      if (res.ok) return { publicKey, alreadyFunded: false };
      // Friendbot returns 400 with "createAccountAlreadyExist" for a funded account.
      if (res.status === 400 && /already|exist/i.test(text)) {
        return { publicKey, alreadyFunded: true };
      }
      lastError = new Error(`friendbot ${res.status}: ${text.slice(0, 200)}`);
    } catch (e) {
      lastError = e as Error;
    }
    if (attempt < attempts - 1) await sleep(baseDelayMs * 2 ** attempt);
  }
  throw new Error(`friendbot funding failed for ${publicKey}: ${lastError?.message ?? "unknown error"}`);
}
